-- Migration 010: Players table + real couple data seeded from xlsx
-- Generated automatically from premier-padel-players.xlsx

-- ============================================================
-- 1. CREATE PLAYERS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS players (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name TEXT NOT NULL,
  last_name  TEXT NOT NULL,
  email      TEXT UNIQUE,
  centre     TEXT,
  department TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_players_email ON players(email);

-- ============================================================
-- 2. ADD PLAYER FK COLUMNS TO COUPLES (if not already added)
-- ============================================================
ALTER TABLE couples
  ADD COLUMN IF NOT EXISTS player_1_id UUID REFERENCES players(id),
  ADD COLUMN IF NOT EXISTS player_2_id UUID REFERENCES players(id);

-- ============================================================
-- 3. SEED PLAYERS
-- ============================================================
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('0247f3e5-0247-4200-4dd4-0c8058e13640','Ruben','Alejo','ralejo@rubatec.cat','Viladecans','Manteniment') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('9ccecc91-9cce-4a00-73e7-0e809a367200','Jordi Amin','Lahsini','jamin@rubatec.cat','Viladecans','Manteniment') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('70f8e50c-70f8-4200-61bd-7680bd07a000','Eloi','Caparrós','ecaparros@rubatec.cat','Viladecans','Manteniment') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('0cc73e7e-0cc7-4000-f1ce-0980f591ce00','Mauricio','Galindo','mgalindo@rubatec.cat','Viladecans','Manteniment') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('5af58ff7-5af5-4200-536d-b980acc29a80','Ismael','Valderas','ivalderas@rubatec.cat','Viladecans','Manteniment') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('62967d4d-6296-4200-eebf-cd001dab9f00','Fermin','Urzainqui','furzainqui@rubatec.cat','Viladecans','Manteniment') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('03644ff0-0364-4d00-6678-5c0017092e00','Albert','Postigo','apostigo@rubatec.cat','Viladecans','Edificació') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('b04fb736-b04f-4800-52c2-d680e9e7b900','Enrique','Barrau','ebarrau@rubatec.cat','Viladecans','Edificació') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('91dd1a95-91dd-4800-7b58-1280330abc00','Isacó','Pérez','iperez@rubatec.cat','Viladecans','Edificació') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('f2b6f4e1-f2b6-4a00-13c0-8e006f97d000','Miguel Ángel','Abad','maabad@rubatec.cat','Viladecans','Edificació') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('4ccd6c5b-4ccd-4000-47c2-a30002840200','Manuel','Tejeda','mtejeda@rubatec.cat','Viladecans','Edificació') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('dc6940f9-dc69-4000-ea35-860079c77e00','Daniel','Alejandre','dalejandre@rubatec.cat','Viladecans','Edificació') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('ba064d15-ba06-4200-3ae1-bc8018062280','Claudio','Marras','cmarras@rubatec.cat','Viladecans','Edificació') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('86679eff-8667-4a00-5bdd-e5009aab4200','Marcelo','Viglione','mviglione@rubatec.cat','Viladecans','Edificació') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('bb8e1a66-bb8e-4a00-f925-5980564f7480','Juan Manuel','Melgar','jmelgar@rubatec.cat','Viladecans','Edificació') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('ed1d9794-ed1d-4600-4d60-1b006e2140c0','Albert','Vidal','avidal@rubatec.cat','Cornellà','Administració') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('c86990a1-c869-4aa0-9960-fa806aa6fe00','Ester','Garcia','egarcia@rubatec.cat','Cornellà','Fotovoltaica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('6e71c59c-6e71-48f2-61f0-6300572f6650','Raquel','Collado','rcollado@rubatec.cat','Cornellà','Fotovoltaica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('e956032d-e956-4800-c36b-e50022d3e650','Juan','Florido','jflorido@rubatec.cat','Cornellà','Fotovoltaica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('0275b933-0275-4900-7030-9700a9726200','Pol','Rubio','prubio@rubatec.cat','Cornellà','Fotovoltaica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('d70935c0-d709-4800-c8f9-1d80217d1200','Aixa','Vilatte','avilatte@rubatec.cat','Cornellà','Fotovoltaica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('1cb1f276-1cb1-4e00-cbd3-5680493d8a40','Sofia','Martín','smartin@rubatec.cat','Cornellà','Fotovoltaica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('36bf535e-36bf-4800-397f-8180c4d11200','Eric','Alonso','ealonso@rubatec.cat','Cornellà','Fotovoltaica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('be5b3df5-be5b-4fc0-4fcb-7d00af0c4400','Carme','Castells','ccastells@rubatec.cat','Cornellà','Enllumenat') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('7488bb29-7488-4600-9443-40004865cc00','Oscar','Martinez','omartinez@rubatec.cat','Cornellà','Enllumenat') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('57dba589-57db-4d00-5a7d-858020c3fbc0','Alexander','García','alexgarcia@rubatec.cat','Cornellà','Oficina Tècnica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('e56021d9-e560-4200-ef81-e8008892d200','Lluc','Basalobre','lbasalobre@rubatec.cat','Cornellà','Oficina Tècnica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('84b41d24-84b4-4500-b08c-b08014b9c600','Daniel','Crespo','dcrespo@rubatec.cat','Cornellà','Oficina Tècnica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, centre, department) VALUES ('a1980d11-a198-4200-dea0-1a0033795200','Enric','Solares','UTE','Enllumenat') ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('42f12ef3-42f1-4800-6475-698039759a00','Quim','Alloza','qalloza@rubatec.cat','Cornellà','Oficina Tècnica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('3b841ca1-3b84-4600-5217-6e0067525680','David','Gordillo','dgordillo@rubatec.cat','Cornellà','Oficina Tècnica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('e4faa2f5-e4fa-4400-ee11-e380139c1c00','Joel','Gómez','jgomez@rubatec.cat','Cornellà','Administració') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('31685a54-3168-4a80-d8de-2580fc0e6d40','Sergi','Somavilla','ssomavilla@rubatec.cat','Cornellà','Delegació') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('cb908863-cb90-4600-97c3-a9006810b600','Oriol','Reyes','oreyes@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('e9c07cd8-e9c0-4c00-c59a-6f004ca4c600','Jordi','Pedrero','jpedrero@rubatec.cat','Cornellà','Fotovoltaica') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, centre, department) VALUES ('f4f5f21f-f4f5-4c00-b25e-9e80ec347e00','Sergio','Vergillo','Cornellà','Facilities') ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('3b99ca78-3b99-4400-a3ef-5b0004ebc800','Marcos','Alcalà','malcala@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('249d4c91-249d-4d00-7668-c3009088ea00','Jordi Alejandro','Farre','jfarre@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, centre, department) VALUES ('a890bb55-a890-4000-f37f-400089b03a00','David','Alexandre','Cornellà','Facilities') ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('5ce9b30f-5ce9-4200-c84d-bc8062ac4c00','David','Aguilar','daguilar@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('5634cb8d-5634-4400-1f52-6f80b6444200','Rubén','Membrilla','rmembrilla@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, centre, department) VALUES ('0f3f80ba-0f3f-4c00-3676-a18070205200','Sergio','Quesada','Cornellà','Facilities') ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('1fcd0ccd-1fcd-4a00-1cf9-f4801cba2a00','Juan Manuel','Martín','jmartin@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('fca81c6b-fca8-4780-23be-0c8016b58a00','Xavier','Ases','xases@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('6d6ca4fa-6d6c-4e00-f826-b5003424f000','Aaron Ali','Majeed','amajeed@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('f2cf2bfd-f2cf-4100-8480-1580f1e20400','Hugo','de Haro','hdeharo@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('8da0241d-8da0-4600-5886-9a8092074e00','Andres','Pérez','aperez@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('47ae79a2-47ae-4100-093a-1f00603b1600','Edgar','Delgado','edelgado@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('57c1e682-57c1-4000-6338-b780c96aa680','Cristian','Carro','ccarro@rubatec.cat','Cornellà','Facilities') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('28e563e1-28e5-4000-dca4-f7800c9aee00','Rubén','Fontarosa','rfontarosa@rubatec.cat','Singulars','Mossos') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, centre, department) VALUES ('6b6e816c-6b6e-4c70-41b1-e880aea97000','Joan','Bautista','Singulars','Mossos') ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, first_name, last_name, centre, department) VALUES ('7c592b65-7c59-4f70-1eba-86006b312d40','Ricard','Vilella','Singulars','Mossos') ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('50ab119f-50ab-4400-a8aa-5c0062f8c500','Alberto','González','agonzalez@rubatec.cat','Singulars','Mossos') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('aff12059-aff1-4500-d587-b0801b411a00','Marc','Vigo','marcvigo@rubatec.cat','Singulars','Mossos') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, centre, department) VALUES ('1941f294-1941-4580-1d39-88005a5d1cc0','Sonia','Ramírez','Singulars','Mossos') ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('3f641e4a-3f64-4c00-ef6f-e58058dc6900','Pedro','Bajatierra','pbajatierra@rubatec.cat','Singulars','Delegació') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('e983b3bf-e983-4700-87e5-e60043b2b200','Maribel','Carrasco','mcarrasco@rubatec.cat','Motors 2','Depuració') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('d02d3351-d02d-4500-ad94-e980a0ba1000','Maite','Bujaldón','mbujaldon@rubatec.cat','Motors 1','Motors 1') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('64fb26e0-64fb-4000-0a1c-49807f67d200','Jordi','Sureda','jsureda@rubatec.cat','Motors 1','Motors 1') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('54a8dc2a-54a8-4000-98b2-4780eb380600','David','Rodado','drodado@rubatec.cat','Motors 1','Motors 1') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('9702f058-9702-4c00-8c9e-a70045acf600','Gerard','Martí','gmarti@rubatec.cat','Motors 1','Motors 1') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('cec11dc2-cec1-4580-d19d-770036968800','Joan','Pujol','jpujol@rubatec.cat','Motors 1','Motors 1') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('7da1a940-7da1-4200-e602-3880532cdca0','Maximiliano','Cooke','mcooke@rubatec.cat','Motors 1','Motors 1') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('1d274a45-1d27-4e00-cf73-a0005599c000','Arnau','Solé','asole@rubatec.cat','Motors 1','Motors 1') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('c79112df-c791-4800-6ab0-c400de811200','Arnau','Costa','acosta@rubatec.cat','Motors 1','Motors 1') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('7131b2b5-7131-4700-1133-1900a5159240','Ivan','Katavich','ikatavich@rubatec.cat','Motors 1','Motors 1') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('d3f5462f-d3f5-4000-ffa4-4b002d42f000','Fernando','Giéenez','fgimenez@rubatec.cat','Motors 1','Motors 1') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('473d2497-473d-4a00-a14e-d4809431e400','Joan','Martínez','jmartinez@rubatec.cat','Motors 2','Motors') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('15bbb545-15bb-4e00-8bdd-eb800c536a00','Alex','Matas','amatas@rubatec.cat','Motors 2','Motors') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('c1e99050-c1e9-4120-08c7-9c803ae98a00','Oscar','Ferre','oferre@rubatec.cat','Motors 2','Motors') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('a9eb6428-a9eb-4a00-1bae-fb80559629c0','José','Pila','jpila@rubatec.cat','Motors 2','Motors') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('79a62fcc-79a6-4c00-93f0-f80084fe5200','Rodrigo','Talavera','rtalavera@rubatec.cat','Motors 2','Motors') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('5a196840-5a19-4200-db8f-0c0031458200','Francisco','Lafosse','flafosse@rubatec.cat','Motors 2','Motors') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('a39bcdde-a39b-47c0-fea5-9180aa826600','Sergi','Ríos','srios@rubatec.cat','Motors 2','Depuració') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('62be1312-62be-4400-6c40-e080abb6e600','Guillem','Mensa','gmensa@rubatec.cat','Trueta','Trueta') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('ef349fb3-ef34-4900-c316-eb803fdae000','Damaris','Alavé','palave@rubatec.cat','Motors 2','Motors') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('fc1c852d-fc1c-4800-ef85-1300b50cdc00','Ricard','Bargalló','rbargallo@rubatec.cat','Trueta','Administració') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('dea4a452-dea4-4400-ff88-db001c1b7e00','Jordi','Tapia','jtapia@rubatec.cat','Trueta','Estudis') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('b6a1b762-b6a1-4500-6b41-a200c793ca40','Carlos','Moreno','cmoreno@rubatec.cat','Trueta','Estudis') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('b2f9e820-b2f9-4400-617e-64000f16b400','Joan','Prósper','jprosper@rubatec.cat','Trueta','Estudis') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('904ed467-904e-4400-9ea2-3000c864d800','Pablo','Frontera','pfrontera@rubatec.cat','Trueta','Direcció') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('c2c90f5d-c2c9-4c00-1942-b0800874e600','Gerard','Garcia','ggarcia@rubatec.cat','Trueta','Desenvolupament') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('da8caa2d-da8c-4000-f583-dc80432a01c8','Guillem','Garcia','guillemgarcia@rubatec.cat','Trueta','Desenvolupament') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('cd577b78-cd57-4800-d235-6980a213a280','Esther','Mateos','emateos@rubatec.cat','Trueta','Estudis') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('0fd8043c-0fd8-4e00-377b-e100ae4ec800','Aina','Rodríguez','ainarodriguez@rubatec.cat','Trueta','Estudis') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('88713e1a-8871-4c00-c1cf-7280b84bea00','Victor','Ramón','vramon@rubatec.cat','Trueta','Administració') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('170a42a7-170a-4400-5f10-5000597f7e00','Mariona','Oliver','moliver@rubatec.cat','Trueta','Estudis') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, centre, department) VALUES ('fb1f9672-fb1f-4a00-b3b8-7f009ea13c00','Raquel','Sánchez','Trueta','PRL-RRHH') ON CONFLICT (id) DO NOTHING;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('7d9cc293-7d9c-4580-e127-d400ac396a00','Anna','Benavides','abenavides@rubatec.cat','Trueta','PRL-RRHH') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('b3a5282f-b3a5-4800-709c-3f803d597400','Gloria','Martínez','gmartinez@rubatec.cat','Trueta','PRL-RRHH') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('9fe24d9b-9fe2-4200-ba95-d700a9739e00','Marc','Tur','mtur@rubatec.cat','Trueta','PRL-RRHH') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('75fce4c7-75fc-4600-110b-1580dc98e000','Joan','Martínez Jr.','joanmartinez@rubatec.cat','Trueta','PRL-RRHH') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('1bce1bd6-1bce-4400-dccd-31005ff8bac0','Santiago','García','sgarcia@rubatec.cat','Trueta','Desenvolupament') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('057f9e37-057f-4200-92d9-8500f585e200','Pablo','de Mora','pdemora@rubatec.cat','Trueta','Desenvolupament') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('a204e9f5-a204-4200-782b-6080e2223200','Alejandro','Alcalde','aalcalde@rubatec.cat','Motors 2','Motors') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('a475f30b-a475-4f80-ccc0-89005819c800','Miquel','Campabadal','mcampabadal@rubatec.cat','Motors 2','Administració') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('caf02113-caf0-4400-41a0-3680a132b400','Alejandro','San Miguel','asanmiguel@rubatec.cat','Viladecans','Administració') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;
INSERT INTO players (id, first_name, last_name, email, centre, department) VALUES ('21977581-2197-44f2-2354-1700dc7a7680','Raúl','Segado','rsegado@rubatec.cat','Motors 2','Motors') ON CONFLICT (email) DO UPDATE SET first_name=EXCLUDED.first_name, last_name=EXCLUDED.last_name, centre=EXCLUDED.centre, department=EXCLUDED.department;

-- ============================================================
-- 4. CLEAR OLD DUMMY DATA, INSERT REAL COUPLES
-- ============================================================
DELETE FROM group_standings;
DELETE FROM match_log;
DELETE FROM matches;
DELETE FROM users;
DELETE FROM couples;

INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Delgado / Majeed','Edgar Delgado','Aaron Majeed','47ae79a2-47ae-4100-093a-1f00603b1600','6d6ca4fa-6d6c-4e00-f826-b5003424f000','diamant','G1',1,'D3 Facilities');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Garcia / Reyes','Ester Garcia','Oriol Reyes','c86990a1-c869-4aa0-9960-fa806aa6fe00','cb908863-cb90-4600-97c3-a9006810b600','diamant','G1',2,'D3 Facilities');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Ramón / Martínez','Víctor Ramon Zamora','Joan Martínez (PRL)','88713e1a-8871-4c00-c1cf-7280b84bea00','473d2497-473d-4a00-a14e-d4809431e400','diamant','G1',3,'Trueta Admin /Trueta PRL');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Postigo / Tejeda','Albert Postigo','Manuel Tejera','03644ff0-0364-4d00-6678-5c0017092e00','4ccd6c5b-4ccd-4000-47c2-a30002840200','diamant','G1',4,'D3 Edificació');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Lahsini / Valderas','Jordi Amin','Ismael Valderas','9ccecc91-9cce-4a00-73e7-0e809a367200','5af58ff7-5af5-4200-536d-b980acc29a80','diamant','G2',1,'D3 Manteniment');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Martínez / Bujaldón','Joan Martínez','Maite Bujaldon','473d2497-473d-4a00-a14e-d4809431e400','d02d3351-d02d-4500-ad94-e980a0ba1000','diamant','G2',2,'Motors 2');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Talavera / Farre','Rodrigo Talavera','Jordi Farre','79a62fcc-79a6-4c00-93f0-f80084fe5200','249d4c91-249d-4d00-7668-c3009088ea00','diamant','G2',3,'Motors 2 / Facilities');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Ríos / Carrasco','Sergi Rios','Maribel Carrasco','a39bcdde-a39b-47c0-fea5-9180aa826600','e983b3bf-e983-4700-87e5-e60043b2b200','diamant','G2',4,'Motors 2');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Somavilla / Bajatierra','Sergi Somavilla','Pedro Bajatierra','31685a54-3168-4a80-d8de-2580fc0e6d40','3f641e4a-3f64-4c00-ef6f-e58058dc6900','diamant','G3',1,'');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Matas / Bargalló','Alex Matas','Ricard Bargalló','15bbb545-15bb-4e00-8bdd-eb800c536a00','fc1c852d-fc1c-4800-ef85-1300b50cdc00','diamant','G3',2,'');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Campabadal / Segado','Miquel Campabadal','Raul Sesgado','a475f30b-a475-4f80-ccc0-89005819c800','21977581-2197-44f2-2354-1700dc7a7680','diamant','G3',3,'');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Vilella / Batista','Ricard Vilella','Joan Batista',NULL,NULL,'diamant','G3',4,'Singulars');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Membrilla / Quesada','Ruben Membrilla','Sergio Quesada','5634cb8d-5634-4400-1f52-6f80b6444200',NULL,'or','G1',1,'D3 Facilities');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Vergillo / Alcalà','Sergio Vergillo','Marcos Alcalá',NULL,'3b99ca78-3b99-4400-a3ef-5b0004ebc800','or','G1',2,'D3 Facilities');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Ases / de Haro','Xavier Ases','Hugo de Haro','fca81c6b-fca8-4780-23be-0c8016b58a00','f2cf2bfd-f2cf-4100-8480-1580f1e20400','or','G1',3,'D3 Facilities');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Frontera / Prósper','Pablo Frontera','Joan Prosper','904ed467-904e-4400-9ea2-3000c864d800','b2f9e820-b2f9-4400-617e-64000f16b400','or','G1',4,'Trueta');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('García / Mensa','Santiago Garcia','Guillem Mensa','1bce1bd6-1bce-4400-dccd-31005ff8bac0','62be1312-62be-4400-6c40-e080abb6e600','or','G2',1,'Trueta');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Vidal / Castells','Albert Vidal','Carme Castells','ed1d9794-ed1d-4600-4d60-1b006e2140c0','be5b3df5-be5b-4fc0-4fcb-7d00af0c4400','or','G2',2,'D3 EP');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Rubio / Collado','Pol Rubio','Raquel Collado','0275b933-0275-4900-7030-9700a9726200','6e71c59c-6e71-48f2-61f0-6300572f6650','or','G2',3,'D3 FV');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Moreno / Tapia','Carlos Moreno','Jordi Tapia','b6a1b762-b6a1-4500-6b41-a200c793ca40','dea4a452-dea4-4400-ff88-db001c1b7e00','or','G2',4,'Trueta Estudis');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Basalobre / Gordillo','Lluc Basobre','David Gordillo','e56021d9-e560-4200-ef81-e8008892d200','3b841ca1-3b84-4600-5217-6e0067525680','or','G3',1,'D3 OFTEC');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('García / Martinez','Alex Garcia','Oscar Martínez','57dba589-57db-4d00-5a7d-858020c3fbc0','7488bb29-7488-4600-9443-40004865cc00','or','G3',2,'D3 OFTEC / EP');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Crespo / Vigo','Dani Crespo','Marc Vigo','84b41d24-84b4-4500-b08c-b08014b9c600','aff12059-aff1-4500-d587-b0801b411a00','or','G3',3,'D3 OFTEC / Singulars');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Tur / de Mora','Marc Tur','Pablo de Mora','9fe24d9b-9fe2-4200-ba95-d700a9739e00','057f9e37-057f-4200-92d9-8500f585e200','or','G3',4,'Trueta PRL / Desenvolupament');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Urzainqui / Galindo','Fermin Urzainqui','Mauricio Galindo','62967d4d-6296-4200-eebf-cd001dab9f00','0cc73e7e-0cc7-4000-f1ce-0980f591ce00','or','G4',1,'D3 Manteniment');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Alejo / Caparrós','Ruben Alejo','Eloi Caparrós','0247f3e5-0247-4200-4dd4-0c8058e13640','70f8e50c-70f8-4200-61bd-7680bd07a000','or','G4',2,'D3 Manteniment');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Sureda / Solé','Jordi Sureda','Arnau Sole','64fb26e0-64fb-4000-0a1c-49807f67d200','1d274a45-1d27-4e00-cf73-a0005599c000','or','G4',3,'Motors 1');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Rodado / Martí','David Rodado','Gerard Marin','54a8dc2a-54a8-4000-98b2-4780eb380600','9702f058-9702-4c00-8c9e-a70045acf600','or','G4',4,'Motors 1');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Cooke / Costa','Maximiliano Coque','Arnau Costa','7da1a940-7da1-4200-e602-3880532cdca0','c79112df-c791-4800-6ab0-c400de811200','or','G5',1,'Motors 1');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Katavich / Giéenez','Ivan Katavich','Francisco Guimenez','7131b2b5-7131-4700-1133-1900a5159240','d3f5462f-d3f5-4000-ffa4-4b002d42f000','or','G5',2,'Motors 1');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Ferre / Pila','Oscar Ferré','José Pila','c1e99050-c1e9-4120-08c7-9c803ae98a00','a9eb6428-a9eb-4a00-1bae-fb80559629c0','or','G5',3,'Motors 2');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Alloza / Solares','Quim Alloza','Enric Solares','42f12ef3-42f1-4800-6475-698039759a00',NULL,'or','G5',4,'D3 OFTEC / Desenvolupament');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Lafosse / Alcalde','Francisco Lafosse','Alex Alcalde','5a196840-5a19-4200-db8f-0c0031458200','a204e9f5-a204-4200-782b-6080e2223200','or','G6',1,'Motors');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('González / Martin','Abert Gonzalez','Xavier Martin','50ab119f-50ab-4400-a8aa-5c0062f8c500',NULL,'or','G6',2,'Mossos');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Garcia / Garcia','Guillem Garcia','Gerard Garcia','da8caa2d-da8c-4000-f583-dc80432a01c8','c2c90f5d-c2c9-4c00-1942-b0800874e600','or','G6',3,'');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Ramirez / Pedrero','Sonia Ramirez','Jordi Pedrero',NULL,'e9c07cd8-e9c0-4c00-c59a-6f004ca4c600','or','G6',4,'Mossos');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Aguilar / Carro','David Aguilar','Cristian Carro','5ce9b30f-5ce9-4200-c84d-bc8062ac4c00','57c1e682-57c1-4000-6338-b780c96aa680','plata','G1',1,'D3 Facilities');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Alexandre / Gómez','David Alexandre','Joel Gómez',NULL,'e4faa2f5-e4fa-4400-ee11-e380139c1c00','plata','G1',2,'D3 Facilities / Admin');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Pérez / Martín','Andrés Pérez','Juan Manuel Martin','8da0241d-8da0-4600-5886-9a8092074e00','1fcd0ccd-1fcd-4a00-1cf9-f4801cba2a00','plata','G1',3,'D3 Facilities');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Alonso / Florido','Eric Alonso','Joan Florido','36bf535e-36bf-4800-397f-8180c4d11200','e956032d-e956-4800-c36b-e50022d3e650','plata','G1',4,'D3 FV');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Martín / Vilatte','Sofia Martin','Aixa Vilatte','1cb1f276-1cb1-4e00-cbd3-5680493d8a40','d70935c0-d709-4800-c8f9-1d80217d1200','plata','G2',1,'D3 FV');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Rodríguez / Oliver','Aina','Mariona','0fd8043c-0fd8-4e00-377b-e100ae4ec800','170a42a7-170a-4400-5f10-5000597f7e00','plata','G2',2,'Trueta Estudis');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Mateos / Sánchez','Esther Mateos','Raquel Sánchez','cd577b78-cd57-4800-d235-6980a213a280',NULL,'plata','G2',3,'Trueta Estudis / Clave');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Benavides / Martínez','Anna Benavida','Gloria Martínez','7d9cc293-7d9c-4580-e127-d400ac396a00','b3a5282f-b3a5-4800-709c-3f803d597400','plata','G2',4,'Trueta PRL');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Pérez / Fontarosa','Isacó Pérez','Ruben Fontarosa','91dd1a95-91dd-4800-7b58-1280330abc00','28e563e1-28e5-4000-dca4-f7800c9aee00','plata','G3',1,'D3 Edificació / Singulars');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Alejandre / Melgar','Daniel Alejandre','Juan Manuel Melgar','dc6940f9-dc69-4000-ea35-860079c77e00','bb8e1a66-bb8e-4a00-f925-5980564f7480','plata','G3',2,'D3 Edificació');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Barrau / Abad','Enrique Barrau','Miguel Angel Abad','b04fb736-b04f-4800-52c2-d680e9e7b900','f2b6f4e1-f2b6-4a00-13c0-8e006f97d000','plata','G3',3,'D3 Edificació');
INSERT INTO couples (team_name,player_1_name,player_2_name,player_1_id,player_2_id,division,group_code,seed,centre) VALUES ('Viglione / Marras','Marcelo Viglione','Claudio Marras','86679eff-8667-4a00-5bdd-e5009aab4200','ba064d15-ba06-4200-3ae1-bc8018062280','plata','G3',4,'D3 Edificació');

-- ============================================================
-- 5. REPLACE AUTH TRIGGER WITH EMAIL-BASED COUPLE LOOKUP
-- ============================================================
DROP TRIGGER IF EXISTS tr_link_test_user ON public.users;
DROP FUNCTION IF EXISTS fn_link_test_user();
DROP TRIGGER IF EXISTS tr_link_user_to_couple ON public.users;
DROP FUNCTION IF EXISTS fn_link_user_to_couple();

CREATE OR REPLACE FUNCTION fn_link_user_to_couple()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_player_id UUID;
  v_couple_id  UUID;
BEGIN
  SELECT id INTO v_player_id FROM players WHERE email = NEW.email;
  IF v_player_id IS NOT NULL THEN
    SELECT id INTO v_couple_id FROM couples
      WHERE player_1_id = v_player_id OR player_2_id = v_player_id
      LIMIT 1;
    IF v_couple_id IS NOT NULL THEN
      NEW.couple_id := v_couple_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER tr_link_user_to_couple
  BEFORE INSERT OR UPDATE OF email ON public.users
  FOR EACH ROW EXECUTE FUNCTION fn_link_user_to_couple();

-- Re-trigger for any existing users
UPDATE public.users SET email = email WHERE email IS NOT NULL;
